apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jpaint
  description: Jpaint is a software component developed by ShashankDatt08, designed to provide painting and drawing functionalities.
  annotations:
    github.com/project-slug: ShashankDatt08/Jpaint
    jira/project-key: SCRUM
    jira/label: backstage-component:jpaint
spec:
  type: application
  owner: ICS
  lifecycle: experimental